#!/usr/bin/env python3

from action_manager import ActionManager
from db_manager import DbManager
from entity_manager import EntityManager
from enums import *
from exceptions import *
from karma_manager import KarmaManager
from log_manager import LogManager
from message_parser import MessageParser
import response_blocks

from logging import Logger
import os

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

app: App = App(token=os.environ.get("SLACK_BOT_TOKEN"))


# Listen for "++" or "--" in any message in any channel the bot subscribes to.
@app.message(r'(\+\+)|(--)')
def handle_karma_grants(message: dict, say) -> None:
    with db_manager.get_db_connection() as conn:
        granter_user_id: str = message['user']
        msg_text: str = message['text']

        valid_user_recipients: list[tuple[str, Action]] = message_parser.detect_valid_user_recipients(msg_text)
        logger.debug("recognized user recipients: " + str(valid_user_recipients))

        invalid_user_recipients: list[tuple[str, Action]] = message_parser.detect_invalid_user_recipients(msg_text)
        logger.debug("unrecognized user recipients: " + str(invalid_user_recipients))

        object_recipients: list[tuple[str, Action]] = message_parser.detect_object_recipients(msg_text)
        logger.debug("object recipients: " + str(object_recipients))

        amount: int
        verb: str

        for recipient in valid_user_recipients:
            recipient_user_id: str = recipient[0]
            action: Action = recipient[1]
            amount, verb = message_parser.get_amount_and_verb(recipient)

            granter_name: str = entity_manager.get_name_from_user_id(granter_user_id)
            recipient_name: str = entity_manager.get_name_from_user_id(recipient_user_id)

            if action == Action.DECREMENT:
                logger.info(f"'{granter_name}' tried to reduce karma of a person with name '{recipient_name}'")
                say('Sorry, you can only remove karma from things (python--), not people (@elvis--)')
                continue

            if recipient_name == granter_name:
                logger.info(f"'{granter_name}' tried to self-grant {amount} karma")
                say(f"Sorry, you can't self-grant karma")
                continue

            try:
                karma_manager.grant_karma(granter_name, recipient_name, amount)
                recipient_total_karma: int = karma_manager.get_karma(recipient_name)
                say(f"<{recipient_name}> {verb}, now has {recipient_total_karma} karma")
            except DisabledEntityError:
                logger.info(f"'{granter_name}' tried to grant karma to disabled entity '{recipient_name}'")
                say(f"Sorry, {recipient_name} isn't participating in Instakarma")

        for recipient in invalid_user_recipients:
            granter_name: str = entity_manager.get_name_from_user_id(granter_user_id)
            recipient_name: str = recipient[0]
            amount, verb = message_parser.get_amount_and_verb(recipient)
            logger.info(f"'{granter_name}' tried to grant '{amount}' karma "
                        f"to unrecognized name '{recipient_name}'")
            say(f"Sorry, I don't recognize the user {recipient_name}")

        for recipient in object_recipients:
            granter_name: str = entity_manager.get_name_from_user_id(granter_user_id)
            recipient_name: str = recipient[0]
            amount, verb = message_parser.get_amount_and_verb(recipient)
            entity_manager.add_object_entity(recipient_name)
            try:
                karma_manager.grant_karma(granter_name, recipient_name, amount)
                recipient_total_karma: int = karma_manager.get_karma(recipient_name)
                say(f"{recipient_name} {verb}, now has {recipient_total_karma} karma.")
            except DisabledEntityError:
                logger.info(f"'{granter_name}' can't grant karma to disabled entity '{recipient_name}'")
                say(f"Sorry, {recipient_name} is not participating in Instakarma")


@app.command('/instakarma')
def handle_instakarma_command(ack, respond, command) -> None:
    ack()
    parameter = command['text'].lower()

    if parameter == 'disable-me':
        action_manager.change_status(command, respond, Status.DISABLED, entity_manager)

    if parameter == 'enable-me':
        action_manager.change_status(command, respond, Status.ENABLED, entity_manager)

    if parameter in ['help', '']:
        action_manager.help(respond)

    if parameter == 'leaderboard':
        action_manager.leaderboard(respond, db_manager)

    if parameter == 'my-stats':
        action_manager.my_stats(command, respond, entity_manager, karma_manager)


if __name__ == "__main__":
    slack_message_handler: SocketModeHandler = SocketModeHandler(app=app, app_token=os.environ["SLACK_APP_TOKEN"])

    logger: Logger = LogManager.get_logger()
    db_manager: DbManager = DbManager(logger, slack_message_handler)
    action_manager: ActionManager = ActionManager(db_manager, logger)
    entity_manager: EntityManager = EntityManager(db_manager, logger, app)
    karma_manager: KarmaManager = KarmaManager(db_manager, entity_manager, logger)
    message_parser: MessageParser = MessageParser(logger)

    db_manager.init_db()

    slack_message_handler.start()  # launch the Slack listener
